### ISSUE TITLE
session_info.py > ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by paxcodes** [PacktPublishing/Web-Development-with-Django#12]
I have Django 3.1 installed.

```
$ sqlite3 --version
3.24.0 2018-06-04 14:10:15 95fbac39baaab1c3a84fdfc82ccb7f42398b2e92f18a2a57bce1d4a713cbaapl

$ sqlite3 db.sqlite3 
sqlite> .schema django_session
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");

sqlite> select * from django_session;
biwuogaylo9c5czycs8o2zjbb2phnchw|.eJxVjMsOwiAQRf-FtSHQoTxcuvcbyAwwUjU0Ke3K-O_apAvd3nPOfYmI21rj1ssSpyzOAsTpdyNMj9J2kO_YbrNMc1uXieSuyIN2eZ1zeV4O9--gYq_f2pFCBkdgkgefk9VsRo2YuDCGYC0DZ7JGERvP3lnQYHhAFcKoB5XE-wP8wDgK:1mCUSv:vqqueaEanWKKwm3Lotc_Se3ggAwPCaMcI5UIQ0oWV30|2021-08-21 22:06:49.448416
3p5jh0gty4rop8niv6gnpjxz0z2tvzv8|.eJxVjMsOwiAQRf-FtSHQoTxcuvcbyAwwUjU0Ke3K-O_apAvd3nPOfYmI21rj1ssSpyzOAsTpdyNMj9J2kO_YbrNMc1uXieSuyIN2eZ1zeV4O9--gYq_f2pFCBkdgkgefk9VsRo2YuDCGYC0DZ7JGERvP3lnQYHhAFcKoB5XE-wP8wDgK:1mCY1Y:y4_p8IpJ8u2JsphmpF6cjcs0duGOXt47y9LoExbR8QQ|2021-08-22 01:54:48.927927
```

Using the `session_info.py` in this repo:

```
$ python session_info.py 'biwuogaylo9c5czycs8o2zjbb2phnchw|.eJxVjMsOwiAQRf-FtSHQoTxcuvcbyAwwUjU0Ke3K-O_apAvd3nPOfYmI21rj1ssSpyzOAsTpdyNMj9J2kO_YbrNMc1uXieSuyIN2eZ1zeV4O9--gYq_f2pFCBkdgkgefk9VsRo2YuDCGYC0DZ7JGERvP3lnQYHhAFcKoB5XE-wP8wDgK:1mCUSv:vqqueaEanWKKwm3Lotc_Se3ggAwPCaMcI5UIQ0oWV30'
Traceback (most recent call last):
  File "/Users/babysleepapp/Code/_learn/_Books/WebDevWithDjango/bookr/session_info.py", line 16, in <module>
    session_dictionary = get_session_dictionary(session_key)
  File "/Users/babysleepapp/Code/_learn/_Books/WebDevWithDjango/bookr/session_info.py", line 8, in get_session_dictionary
    binary_key, payload = base64.b64decode(session_key).split(b':', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by 3h04m1** [comment]
got the same error, did you find the solution?
