### ISSUE TITLE
Ex18.3, step 10: error when migrating, "...module 'bookr.settings' has no attribute 'Prod"

### ISSUE THREAD

**Issue by paxcodes** [PacktPublishing/Web-Development-with-Django#19]
Here is the shell output starting at moving the `bookr` folder to `/home/bookr`, with some commands to show my directory structure, etc.

```sh
pax@bookr:~$ ls
bookr
pax@bookr:~$ ls bookr
book_management  filter_demo      production.conf.sample  static
bookr            manage.py        requirements.txt        templates
bookr_admin      media            reviews
db.sqlite3       production.conf  session_info.py
pax@bookr:~$ sudo mv bookr /home/bookr/
[sudo] password for pax:
pax@bookr:~$ ls
pax@bookr:~$ ls /home/bookr
bookr
pax@bookr:~$ sudo chown -R bookr:bookr /home/bookr/bookr
pax@bookr:~$ ls -al /home/bookr
total 44
drwxr-xr-x  5 bookr bookr 4096 Oct 20 23:29 .
drwxr-xr-x  4 root  root  4096 Oct 20 07:09 ..
-rw-------  1 bookr bookr 1255 Oct 20 23:27 .bash_history
-rw-r--r--  1 bookr bookr  220 Oct 20 07:09 .bash_logout
-rw-r--r--  1 bookr bookr 3771 Oct 20 07:09 .bashrc
drwxrwxr-x 10 bookr bookr 4096 Oct 20 23:26 bookr
drwxrwxr-x  3 bookr bookr 4096 Oct 20 08:22 .cache
drwxrwxr-x  3 bookr bookr 4096 Oct 20 08:21 .local
-rw-r--r--  1 bookr bookr  807 Oct 20 07:09 .profile
-rw-------  1 bookr bookr 6834 Oct 20 23:18 .viminfo
pax@bookr:~$ ls -al /home/bookr/bookr
total 236
drwxrwxr-x 10 bookr bookr   4096 Oct 20 23:26 .
drwxr-xr-x  5 bookr bookr   4096 Oct 20 23:29 ..
drwxrwxr-x  5 bookr bookr   4096 Oct 20 23:26 book_management
drwxrwxr-x  3 bookr bookr   4096 Oct 20 23:26 bookr
drwxrwxr-x  4 bookr bookr   4096 Oct 20 23:26 bookr_admin
-rw-rw-r--  1 bookr bookr 180224 Oct 20 23:26 db.sqlite3
drwxrwxr-x  6 bookr bookr   4096 Oct 20 23:26 filter_demo
-rw-rw-r--  1 bookr bookr    746 Oct 20 23:26 manage.py
drwxrwxr-x  3 bookr bookr   4096 Oct 20 23:26 media
-rw-rw-r--  1 bookr bookr    293 Oct 20 23:26 production.conf
-rw-rw-r--  1 bookr bookr    272 Oct 20 23:26 production.conf.sample
-rw-rw-r--  1 bookr bookr    289 Oct 20 23:26 requirements.txt
drwxrwxr-x  9 bookr bookr   4096 Oct 20 23:26 reviews
-rw-rw-r--  1 bookr bookr    496 Oct 20 23:26 session_info.py
drwxrwxr-x  2 bookr bookr   4096 Oct 20 23:26 static
drwxrwxr-x  4 bookr bookr   4096 Oct 20 23:26 templates
pax@bookr:~$ sudo chmod 600 /home/bookr/bookr/production.conf
pax@bookr:~$ ls -l /home/bookr/bookr/
total 228
drwxrwxr-x 5 bookr bookr   4096 Oct 20 23:26 book_management
drwxrwxr-x 3 bookr bookr   4096 Oct 20 23:26 bookr
drwxrwxr-x 4 bookr bookr   4096 Oct 20 23:26 bookr_admin
-rw-rw-r-- 1 bookr bookr 180224 Oct 20 23:26 db.sqlite3
drwxrwxr-x 6 bookr bookr   4096 Oct 20 23:26 filter_demo
-rw-rw-r-- 1 bookr bookr    746 Oct 20 23:26 manage.py
drwxrwxr-x 3 bookr bookr   4096 Oct 20 23:26 media
-rw------- 1 bookr bookr    293 Oct 20 23:26 production.conf
-rw-rw-r-- 1 bookr bookr    272 Oct 20 23:26 production.conf.sample
-rw-rw-r-- 1 bookr bookr    289 Oct 20 23:26 requirements.txt
drwxrwxr-x 9 bookr bookr   4096 Oct 20 23:26 reviews
-rw-rw-r-- 1 bookr bookr    496 Oct 20 23:26 session_info.py
drwxrwxr-x 2 bookr bookr   4096 Oct 20 23:26 static
drwxrwxr-x 4 bookr bookr   4096 Oct 20 23:26 templates
pax@bookr:~$ sudo -H -u bookr /bin/bash
bookr@bookr:/home/pax$ cd
bookr@bookr:~$ python3 -m virtualenv --python=python3 bookr-venv
created virtual environment CPython3.8.10.final.0-64 in 450ms
  creator CPython3Posix(dest=/home/bookr/bookr-venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/bookr/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
bookr@bookr:~$ source bookr-venv/bin/activate
(bookr-venv) bookr@bookr:~$ pip3 install -r bookr/requirements.txt
Collecting asgiref==3.2.3
  Downloading asgiref-3.2.3-py2.py3-none-any.whl (18 kB)
Collecting dj-database-url==0.5.0
  Using cached dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
Collecting Django==3.0.3
  Downloading Django-3.0.3-py3-none-any.whl (7.5 MB)
     |████████████████████████████████| 7.5 MB 9.1 MB/s
Collecting django-configurations==2.2
  Using cached django_configurations-2.2-py2.py3-none-any.whl (16 kB)
Collecting django-crispy-forms==1.8.1
  Downloading django_crispy_forms-1.8.1-py2.py3-none-any.whl (108 kB)
     |████████████████████████████████| 108 kB 5.2 MB/s
Collecting django-debug-toolbar==2.2
  Downloading django_debug_toolbar-2.2-py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 4.0 MB/s
Collecting django-rest-framework==0.1.0
  Downloading django-rest-framework-0.1.0.tar.gz (969 bytes)
Collecting djangorestframework==3.11.0
  Downloading djangorestframework-3.11.0-py3-none-any.whl (911 kB)
     |████████████████████████████████| 911 kB 5.2 MB/s
Collecting Pillow==7.0.0
  Downloading Pillow-7.0.0-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 3.9 MB/s
Collecting pytz==2019.3
  Downloading pytz-2019.3-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB 7.5 MB/s
Collecting six==1.14.0
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting sqlparse==0.3.0
  Downloading sqlparse-0.3.0-py2.py3-none-any.whl (39 kB)
Collecting gunicorn==20.0.4
  Using cached gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
Processing ./.cache/pip/wheels/35/64/21/9c9e2c1bb9cd6bca3c1b97b955615e37fd309f8e8b0b9fdf1a/psycopg2-2.8.5-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: setuptools>=3.0 in ./bookr-venv/lib/python3.8/site-packages (from gunicorn==20.0.4->-r bookr/requirements.txt (line 13)) (44.0.0)
Building wheels for collected packages: django-rest-framework
  Building wheel for django-rest-framework (setup.py) ... done
  Created wheel for django-rest-framework: filename=django_rest_framework-0.1.0-py3-none-any.whl size=1377 sha256=a09a2f174511c3b1b9889833e1e94c6bbb50ab4906c04420b399d9c5e6b1e8ea
  Stored in directory: /home/bookr/.cache/pip/wheels/5f/6b/cc/126959a66b51f960094ee9ec7c5263d74d91b837341dfd0a59
Successfully built django-rest-framework
Installing collected packages: asgiref, dj-database-url, sqlparse, pytz, Django, six, django-configurations, django-crispy-forms, django-debug-toolbar, djangorestframework, django-rest-framework, Pillow, gunicorn, psycopg2
Successfully installed Django-3.0.3 Pillow-7.0.0 asgiref-3.2.3 dj-database-url-0.5.0 django-configurations-2.2 django-crispy-forms-1.8.1 django-debug-toolbar-2.2 django-rest-framework-0.1.0 djangorestframework-3.11.0 gunicorn-20.0.4 psycopg2-2.8.5 pytz-2019.3 six-1.14.0 sqlparse-0.3.0
(bookr-venv) bookr@bookr:~$ cd bookr
(bookr-venv) bookr@bookr:~/bookr$ export $(cat production.conf | xargs)
(bookr-venv) bookr@bookr:~/bookr$ echo $DJANGO_STATIC_ROOT
/var/www/bookr/static
(bookr-venv) bookr@bookr:~/bookr$ echo $DJANGO_ALLOWED_HOSTS
192.168.1.14
(bookr-venv) bookr@bookr:~/bookr$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    main()
  File "manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/configurations/importer.py", line 159, in load_module
    reraise(err, "Couldn't find configuration '{0}' "
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/configurations/importer.py", line 157, in load_module
    cls = getattr(mod, self.name)
' in module 'bookr':  module 'bookr.settings' has no attribute 'Prod
(bookr-venv) bookr@bookr:~/bookr$
```

Looking at bookr/settings.py, I do have the class `Prod`

```
(bookr-venv) bookr@bookr:~/bookr$ cat bookr/settings.py | grep Prod
class Prod(Dev):
```

I copied all this project's files under Chapter 18 > Exercise 18.3 folder to my repository already. E.g. [wsgi.py](https://github.com/PacktPublishing/Web-Development-with-Django/blob/6a002b5407901a679d6f781be91027720bbec58c/Chapter18/Exercise18.03/bookr/bookr/wsgi.py) is the same as [mine](https://github.com/paxcodes/book_WebDevWithDjango/blob/ex18.3/bookr/bookr/wsgi.py). Also [settings.py](https://github.com/PacktPublishing/Web-Development-with-Django/blob/6a002b5407901a679d6f781be91027720bbec58c/Chapter18/Exercise18.03/bookr/bookr/settings.py) is the [same](https://github.com/paxcodes/book_WebDevWithDjango/blob/ex18.3/bookr/bookr/settings.py).

Any other ideas how to troubleshoot this?

**Comment by beneboy** [comment]
This line is strange:

> ' in module 'bookr':  module 'bookr.settings' has no attribute 'Prod

I would expect it to say something like

`module 'bookr.settings' has no attribute 'Prod'`

i.e. A trailing single quote.

So it seems like it's looking for a class called `Prod ` with a trailing space or some other control character.

You can try running this instead:

```
DJANGO_CONFIGURATION=Prod python3 manage.py migrate
```

To force the environment variable. If that works, then you'll need to check `production.conf` and make sure `DJANGO_CONFIGURATION` isn't being defined in a weird way.
