### ISSUE TITLE
' in module 'bookr':  module 'bookr.settings' has no attribute 'Prod

### ISSUE THREAD

**Issue by samuel-ctrl** [PacktPublishing/Web-Development-with-Django#23]

**Comment by beneboy** [comment]
@samuel-ctrl Hi there, could you let us know at what point you're receiving this error?

**Comment by samuel-ctrl** [comment]
I have this error at production process

**Comment by samuel-ctrl** [comment]
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/configurations/importer.py", line 159, in load_module
    reraise(err, "Couldn't find configuration '{0}' "
  File "/home/bookr/bookr-venv/lib/python3.8/site-packages/configurations/importer.py", line 157, in load_module
    cls = getattr(mod, self.name)
' in module 'bookr':  module 'bookr.settings' has no attribute 'Prod

**Comment by samuel-ctrl** [comment]
pls, anyone help me : (

**Comment by beneboy** [comment]
@samuel-ctrl Looks like you've missed some changes to `manage.py`. Check it matches the code here: https://github.com/PacktPublishing/Web-Development-with-Django/blob/master/Chapter18/final/bookr/manage.py

**Comment by m80b33** [comment]
The same error. Rename everywhere Prod -> Product. Error still told me about 'Prod attribute O_O
