### ISSUE TITLE
Chapter 4 : ModuleNotFoundError: No module named 'admin'

### ISSUE THREAD

**Issue by andreo141** [PacktPublishing/Web-Development-with-Django#31]
After following all the steps of the process of creating a custom admin page, I get the following error:

``
$ python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\..\..\..\Python\Django\venv\lib\site-packages\django\utils\module_loading.py", line 44, in autodiscover_modules
    if register_to:
  File "C:\..\..\..\Python\Django\venv\lib\site-packages\django\utils\functional.py", line 240, in inner
    self._setup()
  File "C:\..\..\..\Python\Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 540, in _setup
    AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
  File "C:\..\..\..\Python\Django\venv\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load       
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'admin'
``

Does anybody know what I'm doing wrong here? I followed the exact same steps and  my file structure should be correct. 

I did notice that the error only occurs when I try to rename 'django.contrib.admin' to reviews.apps.ReviewsAdminConfigin the settings.py file 

When i change it back to 'django.contrib.admin' it suddenly works again, but no custom admin site. :(

**Comment by d-handy** [comment]
It's likely to be an error in the book. I had the same problem and I finally found the solution in the official documentation:
https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#overriding-the-default-admin-site


in `reviews/apps.py`, in the line `default_site = 'admin.BookrAdminSite'` add your project directory (e.g. bookr) in front of `'admin.BookrAdminSite'`: So you should have `default_site = 'bookr.admin.BookrAdminSite'`.



By the way, the code for overriding the default admin site according to the documentation, suggests to store both `admin.py` and `apps.py` int the proejct directory:

_myproject/admin.py_
```
from django.contrib import admin

class MyAdminSite(admin.AdminSite):
    ... 
```

_myproject/apps.py_
```
from django.contrib.admin.apps import AdminConfig

class MyAdminConfig(AdminConfig):
    default_site = 'myproject.admin.MyAdminSite'
```

_myproject/settings.py_
```
INSTALLED_APPS = [
    ...
    'myproject.apps.MyAdminConfig',  # replaces 'django.contrib.admin'
    ...
]
```

**Comment by ChrisGuest** [comment]
There were some breaking changes between Django 3.2 the approach in the book no longer worked.
I had to substantially rewrite this section for the forthcoming 2nd edition.

@orlandocarnate gives a great solution here:
https://github.com/PacktPublishing/Web-Development-with-Django/issues/1
