### ISSUE TITLE
NameError: name 'auth' is not defined after command on page 102 while Migrating the Reviews App

### ISSUE THREAD

**Issue by BansheePrime** [PacktPublishing/Web-Development-with-Django#8]
Please excuse me for taking your time but I'm ony learning and this error little bit too much for me for the moment.

After command:
```(bookr) raspberry@faust:~/latest$ python manage.py makemigrations reviews ```

Output was:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/raspberry/.local/share/virtualenvs/bookr-wLkRGqSc/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/raspberry/.local/share/virtualenvs/bookr-wLkRGqSc/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/raspberry/.local/share/virtualenvs/bookr-wLkRGqSc/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/raspberry/.local/share/virtualenvs/bookr-wLkRGqSc/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/raspberry/.local/share/virtualenvs/bookr-wLkRGqSc/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/raspberry/development/web/bookr/reviews/models.py", line 44, in <module>
    class Review(models.Model):
  File "/home/raspberry/development/web/bookr/reviews/models.py", line 49, in Review
    creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
NameError: name 'auth' is not defined
```

**Comment by beneboy** [comment]
Hi, thanks for your question!

Try adding this line to the top of `models.py` to import the Django `auth` modules:

```python
from django.contrib import auth
```
